"""loyalty_tiers_and_mfa

Revision ID: 60bd1d1ce669
Revises: 372db7311be3
Create Date: 2026-09-30 16:13:01.670915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60bd1d1ce669'
down_revision: Union[str, None] = '372db7311be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_tiers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('min_lifetime_points', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('earn_rate_multiplier', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('mfa_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###
    # NOTE: the 9 "removed index" lines autogenerate flagged here
    # (idx_approvals_status_store, idx_audit_entity, ix_audit_log_created_at,
    # ix_audit_log_entity, idx_campaign_recipients_campaign,
    # idx_movements_product_store, idx_products_name_trgm, idx_products_revision,
    # idx_sales_store_date) are known false positives this session — created via
    # raw SQL elsewhere, not declared as SQLAlchemy Index() objects, so the model
    # diff doesn't see them. None are touched here.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'mfa_secret')
    op.drop_table('loyalty_tiers')
    # ### end Alembic commands ###
